# Generated by Django 4.1.2 on 2022-10-18 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('brand_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='core.carbrand')),
                ('color_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='core.color')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='core.model')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
    ]
