version: '3.3'
services:
  app:
    build: .
    command: python manage.py runserver 0:8000
    volumes:
      - ./avto/:/app/avto/
      - ./api/:/app/api/
      - ./apps/:/app/apps/
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db
    links:
      - db:db
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: hello_django
      POSTGRES_DB: hello_django

    ports:
      - "5432:5432"

